#!/usr/bin/env bash
# personal-nix bootstrap — one-command setup for a fresh Mac.
# Idempotent: safe to re-run.
set -euo pipefail

GITHUB_USER="Pioneer18"
PERSONAL_REPO="https://github.com/${GITHUB_USER}/personal-nix.git"
TEAM_REPO="https://github.com/relymd/dev-environment.git"
USER_SLUG="jonathan-sells"

PROJECTS_DIR="$HOME/projects"
PERSONAL_DIR="$PROJECTS_DIR/personal-nix"
TEAM_DIR="$PROJECTS_DIR/dev-environment"

step() { printf '\n\033[1;34m→ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[1;33m!\033[0m %s\n' "$*"; }
ask()  { printf '\n\033[1;36m?\033[0m %s\n  Press Enter when done (Ctrl-C to abort)... ' "$*"; read -r _; }

# 1. Determinate Nix
step "Checking for Nix"
if command -v nix >/dev/null 2>&1; then
  ok "nix already installed ($(nix --version | head -1))"
else
  warn "nix not found — installing Determinate Nix"
  curl -fsSL https://install.determinate.systems/nix | sh -s -- install --determinate
  # shellcheck disable=SC1091
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  ok "nix installed"
fi

# 2. Team dev-environment
step "Checking for team dev-environment"
if [ -d "$TEAM_DIR" ]; then
  ok "team repo present at $TEAM_DIR"
else
  warn "team repo missing — cloning $TEAM_REPO"
  mkdir -p "$PROJECTS_DIR"
  echo "  (you'll be prompted for GitHub credentials — username + PAT)"
  git clone "$TEAM_REPO" "$TEAM_DIR"
  ok "cloned team repo"
  step "Running team setup.sh (interactive)"
  ( cd "$TEAM_DIR" && ./setup.sh )
fi

# 3. Personal repo
step "Checking for personal-nix repo"
if [ -d "$PERSONAL_DIR" ]; then
  ok "personal-nix present at $PERSONAL_DIR"
  if ! ( cd "$PERSONAL_DIR" && git pull --ff-only ); then
    warn "git pull failed (uncommitted changes?)"
  fi
else
  warn "cloning $PERSONAL_REPO"
  git clone "$PERSONAL_REPO" "$PERSONAL_DIR"
  ok "cloned personal-nix"
fi

# 4. Local slot file (gitignored, lives in team repo)
step "Wiring personal-nix into team's local slot"
HOSTNAME=$(scutil --get ComputerName 2>/dev/null || hostname -s)
LOCAL_SLOT="$TEAM_DIR/users/${USER_SLUG}-${HOSTNAME}-local.nix"
if [ -f "$LOCAL_SLOT" ]; then
  ok "local slot already exists at $LOCAL_SLOT"
else
  cat > "$LOCAL_SLOT" <<EOF
# Gitignored local slot — imports my personal-nix home-manager module.
# Generated by personal-nix bootstrap.sh; safe to edit by hand.
{ ... }:
{
  imports = [ $PERSONAL_DIR ];
}
EOF
  ok "created $LOCAL_SLOT"
fi

# 5. Keychain secrets — interactive pause
step "Keychain secrets check"
NEED_KEYCHAIN_SETUP=0
if security find-generic-password -s claude_code_oauth -a "$USER" -w >/dev/null 2>&1; then
  ok "claude_code_oauth present in Keychain"
else
  warn "claude_code_oauth not in Keychain"
  NEED_KEYCHAIN_SETUP=1
fi
if security find-generic-password -s github_token -a "$USER" -w >/dev/null 2>&1; then
  ok "github_token present in Keychain"
else
  warn "github_token not in Keychain"
  NEED_KEYCHAIN_SETUP=1
fi

if [ "$NEED_KEYCHAIN_SETUP" = "1" ]; then
  cat <<EOF

  Some Keychain items are missing. If iCloud Keychain has already synced from
  another Mac, give it a minute and re-run this script. Otherwise, populate now:

    1. claude setup-token
       (then copy the token)
       security add-generic-password -U -s claude_code_oauth -a \$USER -w '<paste-token>'

    2. Get a GitHub PAT (https://github.com/settings/tokens — repo + workflow scopes)
       security add-generic-password -U -s github_token -a \$USER -w '<paste-pat>'

EOF
  ask "Populate Keychain (or wait for iCloud sync), then continue"
fi

# 6. Apply
step "Running 'dev' to apply config"
cd "$TEAM_DIR"
if command -v dev >/dev/null 2>&1; then
  dev
else
  warn "'dev' wrapper not on PATH — falling back to setup.sh"
  ./setup.sh
fi

# 7. Done
step "Bootstrap complete"
cat <<EOF

  Verify:
    cat ~/.secrets                    # should have CLAUDE_CODE_OAUTH_TOKEN, GITHUB_TOKEN
    claude mcp list                   # should show github, postgres, applescript, filesystem
    ls -la ~/.claude/skills/          # should include symlinks into $PERSONAL_DIR/skills/

EOF
