#!/usr/bin/env bash
# Generated by /tachikoma. Lives at .tachikoma/tachikoma.sh in the project repo.
# Edit at your own risk — re-running /tachikoma will overwrite.

set -e
set -o pipefail

REPO="/Users/pioneer/projects/personal-nix-tachikoma-auto-memory-pruner"
SENTINEL='<promise>COMPLETE</promise>'
ALLOWED_TOOLS='Edit Write Read Glob Grep Bash(git *) Bash(echo *) Bash(grep *)'
PROMPT_FILE="$REPO/.tachikoma/prompt.md"
PROGRESS_FILE="$REPO/.tachikoma/progress.txt"
LOG_FILE="$REPO/.tachikoma/run.log"
PID_FILE="$REPO/.tachikoma/run.pid"
OUTCOME_FILE="$REPO/.tachikoma/outcome"
SHIP_PROMPT_FILE="$REPO/.tachikoma/ship.md"
SHIP_LOG_FILE="$REPO/.tachikoma/ship.log"
ITER_TMP="$REPO/.tachikoma/.iter.tmp"

usage() {
  cat <<EOF
Usage: tachikoma.sh [--dev] --once
       tachikoma.sh [--dev] --afk N

  --once      Run one iteration then stop.
  --afk N     Run up to N iterations (max 50).
  --dev       Dev mode: stream all claude output to the terminal.
              Default (light mode): only structured progress banners are shown.
EOF
  exit 1
}

VERBOSE=0
MODE=""
MAX_ITER=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dev)  VERBOSE=1; shift ;;
    --once) MODE="once"; MAX_ITER=1; shift ;;
    --afk)
      MODE="afk"
      [[ "${2:-}" =~ ^[0-9]+$ ]] || { echo "afk N must be a positive integer" >&2; exit 1; }
      MAX_ITER="$2"
      [ "$MAX_ITER" -le 50 ] || { echo "afk cap exceeds hard ceiling 50" >&2; exit 1; }
      shift 2
      ;;
    *) usage ;;
  esac
done

[[ -n "$MODE" ]] || usage

cd "$REPO"

# Symbol set — fall back to ASCII if locale isn't UTF-8.
if [[ "${LANG:-}${LC_ALL:-}${LC_CTYPE:-}" == *[Uu][Tt][Ff]-8* ]]; then
  SYM_START="🚀" SYM_OK="✓" SYM_ERR="❌" SYM_STOP="⏹" SYM_DONE="🏁" SYM_CAP="⏱" SYM_WARN="⚠"
  RULE_MAIN="═══════════════════════════════════════════════════════════════"
  RULE_ITER="─── iter"
  RULE_SHIP="─── auto-ship"
else
  SYM_START="[start]" SYM_OK="[ok]" SYM_ERR="[err]" SYM_STOP="[stop]" SYM_DONE="[done]" SYM_CAP="[cap]" SYM_WARN="[warn]"
  RULE_MAIN="==============================================================="
  RULE_ITER="--- iter"
  RULE_SHIP="--- auto-ship"
fi

# Lockfile: refuse if a live tachikoma is already running here.
if [ -f "$PID_FILE" ]; then
  EXISTING_PID="$(cat "$PID_FILE" 2>/dev/null || echo "")"
  if [ -n "$EXISTING_PID" ] && kill -0 "$EXISTING_PID" 2>/dev/null; then
    echo "tachikoma already running (pid $EXISTING_PID). Use /tachikoma stop or kill $EXISTING_PID." >&2
    exit 1
  fi
  rm -f "$PID_FILE"
fi
echo $$ > "$PID_FILE"

# Self-heal base_branch metadata if Phase 3 scaffold missed it.
BASE_BRANCH_FILE="$REPO/.tachikoma/base_branch"
if [ ! -f "$BASE_BRANCH_FILE" ]; then
  git rev-parse --abbrev-ref HEAD > "$BASE_BRANCH_FILE"
fi

# Initialise progress file if absent.
[ -f "$PROGRESS_FILE" ] || : > "$PROGRESS_FILE"

OUTCOME="unknown"
ITER=0

cleanup() {
  rm -f "$PID_FILE" "$ITER_TMP"
  echo "$OUTCOME" > "$OUTCOME_FILE"
  notify "$OUTCOME" "$ITER"
}

stop_handler() {
  OUTCOME="stopped"
  {
    echo ""
    echo "$RULE_MAIN"
    echo "  $SYM_STOP STOPPED — received signal at iter $ITER"
    echo "  Run /tachikoma resume to continue, or /tachikoma done to ship what's committed."
    echo "$RULE_MAIN"
    echo ""
  } | tee -a "$LOG_FILE" >&2
  trap - TERM
  cleanup
  printf '\a' >&2 || true
  exit 130
}

notify() {
  local outcome="$1"
  local iters="$2"
  local title="Tachikoma $outcome"
  local body="repo: $(basename "$REPO") · iters: $iters/$MAX_ITER · branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")"
  if command -v osascript >/dev/null 2>&1; then
    ( osascript -e "display notification \"$body\" with title \"$title\"" >/dev/null 2>&1 & ) || true
  fi
  printf '\a' >&2 || true
  echo "[tachikoma] $outcome — $body" | tee -a "$LOG_FILE" >&2
}

# run_claude <prompt_file> <log_file> [extra_tools]
# Runs claude -p. Light mode: output to log only. Dev mode: also streams to terminal.
# Writes output to ITER_TMP. Sets CLAUDE_RC to claude's exit code.
run_claude() {
  local prompt_file="$1"
  local log_file="$2"
  local tools="${3:-$ALLOWED_TOOLS}"

  set +e
  if [ "$VERBOSE" = "1" ]; then
    claude -p "$(cat "$prompt_file")" \
      --allowed-tools "$tools" \
      --add-dir "$REPO" \
      --dangerously-skip-permissions \
      2>&1 | tee -a "$log_file" | tee "$ITER_TMP"
  else
    claude -p "$(cat "$prompt_file")" \
      --allowed-tools "$tools" \
      --add-dir "$REPO" \
      --dangerously-skip-permissions \
      2>&1 | tee -a "$log_file" > "$ITER_TMP"
  fi
  CLAUDE_RC=${PIPESTATUS[0]}
  set -e
}

trap cleanup EXIT
trap stop_handler TERM INT

# Refuse to run on a "main" branch even if the skill missed it.
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
case "$BRANCH" in
  main|master|develop|production)
    echo "[tachikoma] refusing to run on protected branch $BRANCH" >&2
    OUTCOME="error"
    exit 1
    ;;
esac

{
  echo ""
  echo "$RULE_MAIN"
  echo "  $SYM_START starting — repo: $(basename "$REPO") · branch: $BRANCH"
  echo "  cap: $MAX_ITER iter(s) · pid: $$${VERBOSE:+  · mode: dev}"
  echo "$RULE_MAIN"
  echo ""
} | tee "$LOG_FILE"

for ((ITER=1; ITER<=MAX_ITER; ITER++)); do
  echo "$RULE_ITER $ITER / $MAX_ITER ─────────────────────────────────────" | tee -a "$LOG_FILE"

  # Bail if working tree is dirty at iteration start.
  if [ -n "$(git status --porcelain)" ]; then
    echo "[tachikoma] working tree dirty at start of iter $ITER. Bailing — manual cleanup required." | tee -a "$LOG_FILE" >&2
    OUTCOME="error"
    exit 1
  fi

  run_claude "$PROMPT_FILE" "$LOG_FILE"
  RC=$CLAUDE_RC
  RESULT="$(cat "$ITER_TMP" 2>/dev/null || true)"
  rm -f "$ITER_TMP"

  if [ $RC -ne 0 ]; then
    {
      echo ""
      echo "$RULE_MAIN"
      echo "  $SYM_ERR ERROR — claude exited with code $RC at iter $ITER"
      echo "  Run /tachikoma resume to retry, or /tachikoma done to ship what's committed."
      echo "$RULE_MAIN"
      echo ""
    } | tee -a "$LOG_FILE" >&2
    OUTCOME="error"
    exit $RC
  fi

  if [[ "$RESULT" == *"$SENTINEL"* ]]; then
    {
      echo ""
      echo "$RULE_MAIN"
      echo "  $SYM_DONE TACHIKOMA COMPLETE"
      echo "  $ITER iteration(s) · branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")"
      echo "$RULE_MAIN"
      echo ""
    } | tee -a "$LOG_FILE"
    OUTCOME="complete"

    if [ -f "$SHIP_PROMPT_FILE" ]; then
      {
        echo ""
        echo "$RULE_SHIP ──────────────────────────────────────────────────"
        echo ""
      } | tee -a "$LOG_FILE"

      SHIP_TOOLS="Bash(git *) Bash(gh *) Bash(osascript *) Bash(cat *) Bash(echo *) Bash(rm *) Bash(mkdir *) Read Write Edit"
      run_claude "$SHIP_PROMPT_FILE" "$LOG_FILE" "$SHIP_TOOLS"
      # also capture to ship log
      cat "$ITER_TMP" 2>/dev/null >> "$SHIP_LOG_FILE" || true
      SHIP_RC=$CLAUDE_RC
      rm -f "$ITER_TMP"

      if [ $SHIP_RC -ne 0 ]; then
        {
          echo ""
          echo "$RULE_MAIN"
          echo "  $SYM_WARN AUTO-SHIP FAILED (exit $SHIP_RC)"
          echo "  Work is committed on branch: $(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
          echo "  Run /tachikoma done to ship manually."
          echo "$RULE_MAIN"
          echo ""
        } | tee -a "$LOG_FILE"
      fi
    else
      {
        echo "  [ship] ship.md not found — skipping auto-ship. Run /tachikoma done manually."
        echo ""
      } | tee -a "$LOG_FILE"
    fi

    exit 0
  fi

  LAST_LINE="$(tail -n 1 "$PROGRESS_FILE" 2>/dev/null || true)"
  {
    echo ""
    echo "$RULE_MAIN"
    echo "  $SYM_OK MILESTONE — iter $ITER / $MAX_ITER"
    echo "  ${LAST_LINE:-(progress.txt empty)}"
    echo "$RULE_MAIN"
    echo ""
  } | tee -a "$LOG_FILE"
done

{
  echo ""
  echo "$RULE_MAIN"
  echo "  $SYM_CAP CAP HIT — $MAX_ITER iterations without sentinel"
  echo "  Run /tachikoma resume to continue, or /tachikoma done to ship what's committed."
  echo "$RULE_MAIN"
  echo ""
} | tee -a "$LOG_FILE"
OUTCOME="cap"
exit 0
