#!/usr/bin/env bash
# Read secrets from macOS Keychain → write ~/.secrets.
# Called by personal-nix's home.activation.secretsFromKeychain on every rebuild.
# Safe to run by hand for re-generation: scripts/secrets-from-keychain.sh
set -euo pipefail

OUT="$HOME/.secrets"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<'HEADER'
# ~/.secrets — generated by personal-nix from macOS Keychain.
# Do not edit by hand; changes will be overwritten on next 'dev' rebuild.
# To update a secret (the -A is required for activation context to read):
#   security add-generic-password -A -U -s <name> -a $USER -w '<value>'
# To regenerate this file:
#   ~/projects/personal-nix/scripts/secrets-from-keychain.sh
HEADER

missing=0

read_keychain() {
  local svc="$1"
  local var="$2"
  if val=$(/usr/bin/security find-generic-password -s "$svc" -a "$USER" -w 2>/dev/null); then
    printf 'export %s=%q\n' "$var" "$val" >> "$TMP"
    echo "  ✓ $var (Keychain item: $svc)"
  else
    echo "  ✗ Keychain item '$svc' not found" >&2
    echo "    Populate with: security add-generic-password -A -U -s $svc -a \$USER -w '<value>'" >&2
    echo "    (The -A flag is required so home-manager activation can read it.)" >&2
    missing=1
  fi
}

echo "→ Reading secrets from Keychain"
read_keychain "claude_code_oauth" "CLAUDE_CODE_OAUTH_TOKEN"
read_keychain "github_token" "GITHUB_TOKEN"

# Aliases for tools that look for different env var names.
{
  echo ''
  echo '# Aliases'
  # SC2016: literal $GITHUB_TOKEN, expanded at source time
  # shellcheck disable=SC2016
  echo 'export GH_TOKEN="$GITHUB_TOKEN"'
  # github-mcp-server requires this exact env var name
  # shellcheck disable=SC2016
  echo 'export GITHUB_PERSONAL_ACCESS_TOKEN="$GITHUB_TOKEN"'
} >> "$TMP"

# Atomic move with locked-down perms (sourced files don't need x).
chmod 600 "$TMP"
mv "$TMP" "$OUT"
echo "→ Wrote $OUT"

if [ "$missing" = "1" ]; then
  echo ""
  echo "  Some Keychain items are missing — see warnings above."
  echo "  Populate them, then re-run this script (or 'dev')."
  exit 0  # non-fatal so home-manager activation doesn't abort
fi
